"use client"
import React, { useState } from 'react'
import { Button } from '../ui/button'
import { Input } from '../ui/input'
import { Label } from '../ui/label'
import { Upload, User, Mail, Briefcase, FileText, Brain } from 'lucide-react'
import { invoke } from '@tauri-apps/api/core'
import { useRouter } from 'next/navigation'
import { useAppStore } from '@/store/app.store'

export default function CandidateLoginClient() {
  const router = useRouter()
  const setResumeFile = useAppStore((state) => state.setResumeFile)
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    position: '',
  })
  const [resumeFile, setResumeFileLocal] = useState<File | null>(null)
  const [dragOver, setDragOver] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    
    const candidateData = {
      id: '', // Generated by Rust if empty
      name: formData.name,
      role: formData.position,
      status: 'Pending',
      score: null,
      date: new Date().toISOString()
    }

    try {
      await invoke('save_candidate', { candidate: candidateData })
      localStorage.setItem('candidateData', JSON.stringify({
        ...formData,
        resumeFile: resumeFile?.name || null,
      }))
      
      // Save the actual File object to the store for parsing in the next screen
      if (resumeFile) {
        setResumeFile(resumeFile)
      }
      
      router.push('/resume-parsing')
    } catch (err) {
      console.error('Failed to save candidate', err)
    } finally {
      setLoading(false)
    }
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setDragOver(false)
    const file = e.dataTransfer.files?.[0]
    if (file && file.type === 'application/pdf') {
      setResumeFileLocal(file)
    }
  }

  return (
    <div className="min-h-screen bg-[var(--background)] bg-mesh flex items-center justify-center p-4 relative overflow-hidden">
      <div className="absolute top-1/4 left-1/3 w-96 h-96 bg-indigo-500/8 rounded-full blur-3xl" />
      <div className="absolute bottom-1/3 right-1/4 w-80 h-80 bg-purple-500/8 rounded-full blur-3xl" />

      <div className="glass rounded-2xl max-w-lg w-full animate-fade-in-up overflow-hidden">
        {/* Header */}
        <div className="bg-gradient-to-r from-indigo-500/10 to-purple-500/10 border-b border-white/[0.06] px-8 py-6">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-white">Candidate Login</h1>
              <p className="text-white/40 text-xs">Provide your details to begin</p>
            </div>
          </div>
        </div>

        {/* Form */}
        <div className="p-8">
          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="space-y-1.5">
              <Label className="text-white/50 text-xs font-medium flex items-center gap-2">
                <User className="w-3.5 h-3.5" /> Full Name
              </Label>
              <Input
                id="name"
                placeholder="John Doe"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                required
                className="bg-white/[0.04] border-white/[0.08] text-white placeholder:text-white/20 rounded-xl focus:border-indigo-500/40 focus:bg-white/[0.06] transition-all"
              />
            </div>

            <div className="space-y-1.5">
              <Label className="text-white/50 text-xs font-medium flex items-center gap-2">
                <Mail className="w-3.5 h-3.5" /> Email Address
              </Label>
              <Input
                id="email"
                type="email"
                placeholder="john.doe@email.com"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                required
                className="bg-white/[0.04] border-white/[0.08] text-white placeholder:text-white/20 rounded-xl focus:border-indigo-500/40 focus:bg-white/[0.06] transition-all"
              />
            </div>

            <div className="space-y-1.5">
              <Label className="text-white/50 text-xs font-medium flex items-center gap-2">
                <Briefcase className="w-3.5 h-3.5" /> Position Applied For
              </Label>
              <Input
                id="position"
                placeholder="Frontend Developer"
                value={formData.position}
                onChange={(e) => setFormData({ ...formData, position: e.target.value })}
                required
                className="bg-white/[0.04] border-white/[0.08] text-white placeholder:text-white/20 rounded-xl focus:border-indigo-500/40 focus:bg-white/[0.06] transition-all"
              />
            </div>

            <div className="space-y-1.5">
              <Label className="text-white/50 text-xs font-medium flex items-center gap-2">
                <FileText className="w-3.5 h-3.5" /> Resume (PDF)
              </Label>
              <div
                onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
                onDragLeave={() => setDragOver(false)}
                onDrop={handleDrop}
                className={`border-2 border-dashed rounded-xl p-6 text-center transition-all duration-200 cursor-pointer ${
                  dragOver
                    ? 'border-indigo-500/50 bg-indigo-500/10'
                    : resumeFile
                    ? 'border-emerald-500/30 bg-emerald-500/5'
                    : 'border-white/10 bg-white/[0.02] hover:border-indigo-500/30 hover:bg-white/[0.04]'
                }`}
              >
                <input
                  id="resume"
                  type="file"
                  accept=".pdf"
                  onChange={(e) => setResumeFileLocal(e.target.files?.[0] || null)}
                  className="hidden"
                />
                <label htmlFor="resume" className="cursor-pointer block">
                  <Upload className={`w-8 h-8 mx-auto mb-2 ${
                    resumeFile ? 'text-emerald-400' : 'text-white/20'
                  }`} />
                  <p className={`text-sm font-medium ${
                    resumeFile ? 'text-emerald-300' : 'text-white/40'
                  }`}>
                    {resumeFile ? resumeFile.name : 'Click to upload or drag and drop'}
                  </p>
                  <p className="text-[11px] text-white/20 mt-1">PDF up to 10MB</p>
                </label>
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className={`w-full py-3 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 text-white font-semibold text-sm shadow-lg shadow-indigo-500/25 hover:shadow-xl hover:shadow-indigo-500/30 hover:scale-[1.02] active:scale-[0.98] transition-all duration-200 mt-2 flex items-center justify-center gap-2 ${
                loading ? 'opacity-70 cursor-not-allowed' : ''
              }`}
            >
              {loading && <Brain className="w-4 h-4 animate-spin" />}
              {loading ? 'Registering...' : 'Continue'}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}
